var offer = [
  {
    "text": "Naan Roti",
    "img": "images/o1.jpg",
    "text2": "Rs. 60",
    "text3": "Rs. 100",
    "rs": "60",
  },
  {
    "text": "Chicken Tandoori",
    "img": "images/o2.jpg",
    "text2": "Rs. 230",
    "text3": "Rs. 300",
    "rs": "230",
  },
  {
    "text": "Kati Roll",
    "img": "images/o3.jpg",
    "text2": "Rs. 160 ",
    "text3": "Rs. 180",
    "rs": "160",
  },
  {
    "text": "Drumstick",
    "img": "images/o4.jpg",
    "text2": "Rs. 250",
    "text3": "Rs. 310",
    "rs": "250",
  },
  {
    "text": "Sandwich",
    "img": "images/o5.jpg",
    "text2": "Rs. 90 ",
    "text3": "Rs. 100",
    "rs": "90",
  },
  {
    "text": "Fries",
    "img": "images/o6.jpg",
    "text2": "Rs. 60",
    "text3": "Rs. 80",
    "rs": "60",
  },
  {
    "text": "Chicken Curry",
    "img": "images/o7.jpg",
    "text2": "Rs. 250",
    "text3": "Rs. 300",
    "rs": "250",
  },
  {
    "text": "Chicken Manchurian",
    "img": "images/o8.jpg",
    "text2": "Rs. 280",
    "text3": "Rs. 320",
    "rs": "280",
  },
  {
    "text": "Egg Curry",
    "img": "images/o9.jpg",
    "text2": "Rs. 160",
    "text3": "Rs. 200",
    "rs": "160",
  },
  {
    "text": "Thukpa",
    "img": "images/o10.jpg",
    "text2": "Rs. 90",
    "text3": "Rs. 100",
    "rs": "90",
  },
];

var offer2 = [
  {
    "text": "Ramen",
    "img": "images/i14.jpg",
    "text2": "Rs. 560",
    "text3": "Rs. 600",
    "rs": "560",
  },
  {
    "text": "Pizza",
    "img": "images/p10.jpg",
    "text2": "Rs. 450",
    "text3": "Rs. 510",
    "rs": "450",
  },
  {
    "text": "Biryani",
    "img": "images/i4.jpg",
    "text2": "Rs. 300 ",
    "text3": "Rs. 400",
    "rs": "300",
  },
  {
    "text": "Hotdog",
    "img": "images/i2.jpg",
    "text2": "Rs. 160 ",
    "text3": "Rs. 180",
    "rs": "160",
  },
  {
    "text": "Pork Ribs",
    "img": "images/i7.jpg",
    "text2": "Rs. 290",
    "text3": "Rs. 340",
    "rs": "290",
  },
  {
    "text": "Pasta",
    "img": "images/i8.jpg",
    "text2": "Rs. 180",
    "text3": "Rs. 300",
    "rs": "180",
  },
  {
    "text": "Teokboki",
    "img": "images/i13.jpg",
    "text2": "Rs. 420",
    "text3": "Rs. 500",
    "rs": "420",
  },
];
