//Explorefood_khana_list
var data = [
  {
    "name": "Cookies",
    "url": "images/bg-6.jpg",
    "text": "Think Outside the Bun",
    "text2": "Rs. 60",
    "rs" : 60,
  },
  {
    "name": "Salad",
    "url": "images/bg-1.jpg",
    "text": "Healthy food taste better",
    "text2": "Rs. 80",
    "rs" : 80,
  },
  {
    "name": "Mojito",
    "url": "images/s4.jpg",
    "text": "Drink like a fish",
    "text2": "Rs. 160",
    "rs" : 160,
  },
  {
    "name": "Pizza",
    "url": "images/s6.jpg",
    "text": "Eat well feel well",
    "text2": "Rs. 450",
    "rs" : 450,
  },
  {
    "name": "Sandwich",
    "url": "images/img-5.jpg",
    "text": "Taste the passion!",
    "text2": "Rs. 120",
    "rs" : 120,
  },
  {
    "name": "Breakfast",
    "url": "images/tall.jpg",
    "text": "Enjoy in joy!",
    "text2": "Rs. 200",
    "rs" : 200,
  },
];

//Ourfood_list
var list = [
  {
    "text": "Pasta",
    "img": "images/i8.jpg",
    "text2": "Rs. 180",
    "text3": "Rs. 300",
    "rs" : 180,
  },
  {
    "text": "Ramen",
    "img": "images/i14.jpg",
    "text2": "Rs. 560",
    "text3": "Rs. 600",
    "rs" : 560,
  },
  {
    "text": "Bibimbap",
    "img": "images/i12.jpg",
    "text2": "Rs. 290",
    "text3": "Rs. 320",
    "rs" : 290,
  },
  {
    "text": "Hot Choco",
    "img": "images/i9.jpg",
    "text2": "Rs. 260",
    "text3": "Rs. 280",
    "rs" : 260,
  },
  {
    "text": "Burger",
    "img": "images/i1.jpg",
    "text2": "Rs. 230",
    "text3": "Rs. 300",
    "rs" : 230,
  },
  {
    "text": "Hotdog",
    "img": "images/i2.jpg",
    "text2": "Rs. 160 ",
    "text3": "Rs. 180",
    "rs" : 160,
  },
  {
    "text": "Pizza",
    "img": "images/p10.jpg",
    "text2": "Rs. 450",
    "text3": "Rs. 510",
    "rs" : 450,
  },
  {
    "text": "Biryani",
    "img": "images/i4.jpg",
    "text2": "Rs. 300 ",
    "text3": "Rs. 400",
    "rs" : 300,
  },
  {
    "text": "Paratha",
    "img": "images/i5.jpg",
    "text2": "Rs. 80",
    "text3": "Rs. 110",
    "rs" : 80,
  },
  {
    "text": "Pork Ribs",
    "img": "images/i7.jpg",
    "text2": "Rs. 290",
    "text3": "Rs. 340",
    "rs" : 290,
  },
  {
    "text": "Miso Soup",
    "img": "images/i6.jpg",
    "text2": "Rs. 60",
    "text3": "Rs. 100",
    "rs" : 60,
  },
  {
    "text": "Momo",
    "img": "images/i10.jpg",
    "text2": "Rs. 120",
    "text3": "Rs. 200",
    "rs" : 120,
  },
  {
    "text": "Chowmein",
    "img": "images/i11.jpg",
    "text2": "Rs. 90",
    "text3": "Rs. 100",
    "rs" : 90,
  },
  {
    "text": "Teokboki",
    "img": "images/i13.jpg",
    "text2": "Rs. 420",
    "text3": "Rs. 500",
    "rs" : 420,
  },
];

//grid_profile_list
var data2 = [
  {
    "name": "Cookies",
    "url": "images/bg-6.jpg",
    "text": "Rs. 80",
    "rs" :80,
  },
  {
    "name": "Burger",
    "url": "images/i1.jpg",
    "text": "Rs. 100",
    "rs" :100,
  },
  {
    "name": "Pizza",
    "url": "images/i3.jpg",
    "text": "Rs. 290",
    "rs" :290,
  },
  {
    "name": "Biryani",
    "url": "images/i4.jpg",
    "text": "Rs. 300",
    "rs" :300,
  },
  {
    "name": "Paratha",
    "url": "images/i5.jpg",
    "text": "Rs. 50",
    "rs" :50,
  },
  {
    "name": "Momo",
    "url": "images/i10.jpg",
    "text": "Rs. 190",
    "rs" :190,
  },
  {
    "name": "Sandwich",
    "url": "images/img-5.jpg",
    "text": "Rs. 70",
    "rs" :70,
  },
  {
    "name": "Pork Ribs",
    "url": "images/i7.jpg",
    "text": "Rs. 420",
    "rs" :420,
  },
  {
    "name": "Ramen",
    "url": "images/i14.jpg",
    "text": "Rs. 480",
    "rs" :480,
  },
  {
    "name": "Breakfast",
    "url": "images/i9.jpg",
    "text": "Rs. 52",
    "rs" :52,
  },
];
