//section_khana_list
var sec1 = [
  {
    "name": "Newari Khaja Set",
    "url": "images/i3.jpg",
    "text": "Rs. 450",
    "type": "Authentics",
    "rs" : 450,
  },
  {
    "name": "Dhedo",
    "url": "images/bg-3.jpg",
    "text": "Rs. 260",
    "type": "Authentics",
    "rs" : 260,
  },
  {
    "name": "Thakali Khana",
    "url": "images/l3.jpg",
    "text": "Rs. 420",
    "type": "Authentics",
    "rs" : 420,
  },
  {
    "name": "Buff Sukuti",
    "url": "images/sukuti.png",
    "text": "Rs. 100",
    "type": "Authentics",
    "rs" : 100,
  },
  {
    "name": "Num Chum",
    "url": "images/numchum.png",
    "text": "Rs. 100",
    "type": "Authentics",
    "rs" : 100,
  },
  {
    "name": "Ramen",
    "url": "images/i14.jpg",
    "text": "Rs. 560",
    "type": "Authentics",
    "rs" : 560,
  },
  {
    "name": "Tteokbokki",
    "url": "images/i13.jpg",
    "text": "Rs. 420",
    "type": "Authentics",
    "rs" : 420,
  },
  {
    "name": "Bibimbap",
    "url": "images/i12.jpg",
    "text": "Rs. 290",
    "type": "Authentics",
    "rs" : 290,
  },
  {
    "name": "Biryani",
    "url": "images/i4.jpg",
    "text": "Rs. 300",
    "type": "Authentics",
    "rs" : 300,
  },
  {
    "name": "Aaloo Paratha",
    "url": "images/i5.jpg",
    "text": "Rs. 80",
    "type": "Authentics",
    "rs" : 80,
  },
  {
    "name": "Naan Roti",
    "url": "images/o1.jpg",
    "text": "Rs. 60",
    "type": "Authentics",
    "rs" : 60,
  },
  {
    "name": "Momo",
    "url": "images/i10.jpg",
    "text": "Rs. 120",
    "type": "Authentics",
    "rs" : 120,
  },
  {
    "name": "Pork Ribbs",
    "url": "images/i7.jpg",
    "text": "Rs. 290",
    "type": "Authentics",
    "rs" : 290,
  },
  {
    "name": "Pasta",
    "url": "images/i8.jpg",
    "text": "Rs. 150",
    "type": "Authentics",
    "rs" : 150,
  },
  {
    "name": "Sausage Pizza",
    "url": "images/p9.jpg",
    "text": "Rs. 390",
    "type": "Our Pizza",
    "rs" : 390,
  },
  {
    "name": "Masala Pizza",
    "url": "images/p10.jpg",
    "text": "Rs. 250",
    "type": "Our Pizza",
    "rs" : 250,
  },
  {
    "name": "Meatball Pizza",
    "url": "images/p11.jpg",
    "text": "Rs. 360",
    "type": "Our Pizza",
    "rs" : 360,
  },
  {
    "name": "Bacon Egg Pizza",
    "url": "images/p12.jpg",
    "text": "Rs. 400",
    "type": "Our Pizza",
    "rs" : 400,
  },
  {
    "name": "Cheese Pizza",
    "url": "images/p1.jpg",
    "text": "Rs. 290",
    "type": "Our Pizza",
    "rs" : 290,
  },
  {
    "name": "Pepperoni Pizza",
    "url": "images/p2.jpg",
    "text": "Rs. 360",
    "type": "Our Pizza",
    "rs" : 360,
  },
  {
    "name": "Chicken Pizza",
    "url": "images/p3.jpg",
    "text": "Rs. 450",
    "type": "Our Pizza",
    "rs" : 450,
  },
  {
    "name": "Hawaiian Pizza",
    "url": "images/p4.jpg",
    "text": "Rs. 800",
    "type": "Our Pizza",
    "rs" : 800,
  },
  {
    "name": "Desert Pizza",
    "url": "images/p5.jpg",
    "text": "Rs. 300",
    "type": "Our Pizza",
    "rs" : 300,
  },
  {
    "name": "Cone Pizza",
    "url": "images/p6.jpg",
    "text": "Rs. 400",
    "type": "Our Pizza",
    "rs" : 400,
  },
  {
    "name": "Olive Pizza",
    "url": "images/p8.jpg",
    "text": "Rs. 390",
    "type": "Our Pizza",
    "rs" : 390,
  },
  {
    "name": "Mushroom Pizza",
    "url": "images/p7.jpg",
    "text": "Rs.290",
    "type": "Our Pizza",
    "rs" : 290,
  },
  {
    "name": "Mixed Achaar",
    "url": "images/d8.jpg",
    "text": "Rs. 50",
    "type": "Achaar",
    "rs" : 50,
  },
  {
    "name": "Khursani Achaar",
    "url": "images/d1.jpg",
    "text": "Rs. 50",
    "type": "Achaar",
    "rs" : 50,
  },
  {
    "name": "Mula Achaar",
    "url": "images/d7.jpg",
    "text": "Rs. 50",
    "type": "Achaar",
    "rs" : 50,
  },
  {
    "name": "Aap Achaar",
    "url": "images/d3.jpg",
    "text": "Rs. 50",
    "type": "Achaar",
    "rs" : 50,
  },
  {
    "name": "Kaagati Achaar",
    "url": "images/d4.jpg",
    "text": "Rs. 50",
    "type": "Achaar",
    "rs" : 50,
  },
  {
    "name": "Chhop Masala",
    "url": "images/d5.jpg",
    "text": "Rs. 50",
    "type": "Achaar",
    "rs" : 50,
  },
  {
    "name": "Sukuti Achaar",
    "url": "images/sa.png",
    "text": "Rs. 120",
    "type": "Achaar",
    "rs" : 120,
  },
  {
    "name": "Mithi Achaar",
    "url": "images/d2.jpg",
    "text": "Rs. 50",
    "type": "Achaar",
    "rs" : 50,
  },
];
